FROM adoptopenjdk/openjdk11:ubi
ADD target/gerenciamento-pedidos-springframework-0.0.1.jar gerenciamento-pedidos-springframework-0.0.1.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "gerenciamento-pedidos-springframework-0.0.1.jar"]